### ISSUE TITLE
There are no resistors, capacitors ...?

### ISSUE THREAD

**Issue by weeberp** [BrownDogGadgets/CrazyCircuits#2]
Would not it be necessary to include a resistor on the PCB itself? For example for LED (although in arduino you can activate pull-up) to use as output. Or for LDR or use button as input.
And some capacitor for the 555 timer?

https://github.com/BrownDogGadgets/CrazyCircuits/tree/master/Circuit-Kits/Modules/2x2-LED-TH-2.54mm-Pitch
https://github.com/BrownDogGadgets/CrazyCircuits/tree/master/Circuit-Kits/Modules/1x3-Button-Momentary
https://github.com/BrownDogGadgets/CrazyCircuits/tree/master/Circuit-Kits/Modules/2x2-CdS-Photocell-TH
https://github.com/BrownDogGadgets/CrazyCircuits/tree/master/Circuit-Kits/Modules/3x4-555-Timer-8DIP-Breakout
thanks.

**Comment by Joshua-BrownDogGadgets** [comment]
It's not necessary to include one.  Not for the low voltages we're using with the LEDs.  The life of the LED may be diminished a bit, but not in any noticeable way.

We're not getting the LDR or 555 manufactured any time soon, so we're not even thinking about that.

The buttons are fine the way they are.  If someone really wants to add in a resistor for a project they can do so via a screw terminal.  We have a few solutions for how to add in caps or resistors in the future for projects.

**Comment by weeberp** [comment]
Ok, Batery 3V CR2032 and 3,3V for Led is right, but 5V from Arduino Nano, I do not think so, some LEDs if supported by others not.
Screwing it is a good solution.

**Comment by Joshua-BrownDogGadgets** [comment]
We've done a couple of projects using LEDs off our boards WITHOUT resistors and they work fine.  The big issue for most of them is that you will decrease the life of the LEDs.  This may mean that you'll only get 5,000 hours of use out of it instead of 10,000 hours.  That being said, these are inexpensive LEDs so we're not really worried about them.
